### PR TITLE
Support for boolean body parameters

### PR DESCRIPTION
**Pull request by monkeyalive**
Support for boolean body parameters

### CODE REVIEW

**Comment by mariusc23** [comment]
Hi! Thanks for submitting this. Isn't this something thats handled by [body-parser](https://github.com/expressjs/body-parser) though?

**Comment by monkeyalive** [comment]
Yeah, Apparently body-parser isn't handling this. At least not in node v6.10.2, "express": "^4.13.3", and "body-parser": "^1.14.1". 

I will check if I am missing any other configs in body-parser. Thank you.

**Comment by monkeyalive** [comment]
I am using the following code, and its not working for boolean values. Am I missing something?

```
app.use(bodyParser.json()); 
app.use(bodyParser.urlencoded({ extended: true })); 

```

**Comment by mariusc23** [comment]
@upendrasoft Does your request have `Content-Type: application/json` header?

**Comment by monkeyalive** [comment]
No. I used `application/x-www-form-urlencoded` for the endpoint I was testing.

**Comment by motss** [comment]
@upendrasoft For you case, this should work:

```js
...
.use(bodyParser.json())
.use(bodyParser.urlencoded({ extended: false })
...
```

**Comment by monkeyalive** [comment]
I have tried that and it is still not working.

Anyway the 2 PRs are just suggestions. Feel free to decline if they are not required.

**Comment by motss** [comment]
@upendrasoft That's strange. It worked on my Express app. Mind sharing a reduced version of your request body for debugging purposes? Am really interested in finding out why.

**Comment by monkeyalive** [comment]
Here is the code, request and output.

```
'use strict';

var express = require('express'),
    bodyParser = require('body-parser'),
    app = express();


app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false })); 

// Server
var server = app.listen(3001, function() {
    var port = server.address().port;
    console.log('listening on port %d', port);

    app.all('*', function(req, res) {
        console.log('req.body.test is ' + req.body.test)
        console.log('req.query.test is ' + req.query.test)
        var test = req.body.test || req.query.test;
        console.log('test value is' + test);
        console.log('test === \'true\' is ' + (test === 'true'));
        console.log('test === true is ' + (test === true));

        res.send('Success');
    });

});
```
Test using curl or Postman (body of type 'x-www-form-encoded' or 'raw')
```
curl -X POST -d "test=true" 'http://localhost:3001/'
```

Console log output
```
$  node -v
v6.10.2

$ node test-server.js 
listening on port 3001
req.body.test is true
req.query.test is undefined
test value istrue
test === 'true' is true
test === true is false
```

Same as GET with query parameters
```
curl -X GET 'http://localhost:3001/?test=true'
```

console log output
```
req.body.test is undefined
req.query.test is true
test value istrue
test === 'true' is true
test === true is false
```

Hope this helps.

**Comment by motss** [comment]
@upendrasoft Apparently parsing boolean is handled by `body-parser` but only happening when the body type is `application/json`. Whereas `x-www-form-encoded` is parsed by the `qs` module which is the module used to parse query strings and `body-parser` depends on it to parse request body that is in the type of `x-www-form-encoded`. Unless `qs` support that kind of parsing, you can only get that boolean parsing feature in `application/json`. Most of my **POST** endpoints are using `application/json` and it works for me.

***TIL: Use `application/json` if you want that boolean parsing feature in request body***

**Comment by monkeyalive** [comment]
Right. using `application/json` works since we can specify the value type. For booleans one would use `{ 'test': true }` (value without quotes).

I was just suggesting to support booleans for `x-form-www-encoded` as well. especially since there is no way to specify the value type in POST here.

The same problem exists for GET too.
```
curl -X GET 'http://localhost:3001/?test=true' --header 'Content-Type: application/json'
```

output:
```
req.body.test is undefined
req.query.test is true
test value istrue
test === 'true' is true
test === true is false
```

**Comment by mariusc23** [comment]
Parsing the body is beyond the scope of this project. You're welcome to fork and publish your own version that supports parsing the body (I'll even link to it from the readme).

**Pull request closed without merging**
